travis:
  secure:
    BINSTAR_TOKEN: UDzTMM7nP5uSrVRVRGEzH/vJIj7gZ6AvsxTe2n5xnJ3GCnMEbeAf0cdovdKhbQfOT0Tftif3qp2/PawIeT+sZkdmbWdnRViHBl/1Mr93A7TsFzFbsO1vMWskyiigY9Oc/7XVceelOLT3c2cac34KkoWUkRSLWJqQPURDfLPp355vKUawUjEgy8xVJgttSaS/BhsfSdl7ALx0JKDy4VfSgMRjWBsOsX/XV779FijW1aISr49gxszXNtkd9/7A2v0PR22maH5zkQaK0W0S1Zlqx5yXKgKpwHu3m6oYP74KPVJ6LP2+lmxwNHeQ9mjMyVzBxEC+BvLP9naR74XyXRJZrfiaxDz7s2HHd7Zi50YuDYWD+u7+pwkr+qjM3v2diote9FSMLYG65hllfuPy4KdD4THaCR4Rn4fIv1Wvlz3B5ALhq02j+7iIbQXVEE3AxAUbWvveI37BwP1O/6rAOiRtexeqG1rnhJsBnhHHP2IzArbMGUEfzV5vozDty98U2Y6vPXcvjPNj0H7OFa7bSoB4NkpARXpagSTmTvKFZ9RCeCtKndeI4vUpcnad926HCITJjHlnHW3D9n7zwMpJbYQjn8lsSj0+4+zs2FGX9Zr1gvJLqYimn6JziaBTqE5Krv5/DfyjT7GRdeW638Hhl5AqXb+x/Ruo6GZbCUidCk5kWNo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
